strategy: deepspeed_zero2
precision: bf16-mixed
deepy:
  zero_stage: 2
  offload_optimizer_device: none
  offload_param_device: none
accumulate_grad_batches: 1
max_steps: null
log_every_n_steps: 50
val_check_interval: 5000
gradient_clip_val: 1.0
